.travis.yml, app/build.gradle, dependency-suppression.xml, gradle/android-common.gradle, gradle/style.gradle, library/build.gradle, library/publish.gradle, library/src/test/java/com/okta/oidc/clients/SyncAuthClientTest.java, library/src/test/java/com/okta/oidc/clients/sessions/SessionClientImplTest.java
build.gradle fails because local.properties
is missing. This makes a empty local.properties file
before buildling.
=> Fix travis-ci: failing due to missing file.

README.md, library/publish.gradle
Having issues with adding the library to jcenter.
Update gradle file to add the repository for now until this gets fixed.
=> Update README for gradle changes

README.md, build.gradle
=> Update version and readme

library/src/main/java/com/okta/oidc/RequestDispatcher.java
=> Clear task instead of setting to null.

app/src/main/java/com/okta/oidc/example/SampleActivity.java, app/src/main/res/layout/sample_activity.xml
Put login hint back in samples.
=> Fix samples to add login hint

ci-build/default.generated.config, library/publish.gradle
Reverse jetifier that creates a non androidx aar but kept the androidx pom.
This fix makes the correct pom.
=> Reverse jetifier will now create correct pom.

build.gradle
=> Update owasp check to 5.0.0

library/src/test/java/com/okta/oidc/util/AsciiStringListUtilTest.java, library/src/test/java/com/okta/oidc/util/CodeVerifierUtilTest.java, library/src/test/java/com/okta/oidc/util/JsonUtilTest.java, library/src/test/java/com/okta/oidc/util/PreconditionsTest.java, library/src/test/java/com/okta/oidc/util/UriUtilTest.java
Fix for travis-ci failure. Have to add config sdk=27
=> Fix for travis failure

.travis.yml, README.md
=> README: Add discoveryUri notes

library/src/main/java/com/okta/oidc/AuthenticationPayload.java, library/src/test/java/com/okta/oidc/AuthClientPayloadTest.java
This checks the payload state and hint. If null or empty is provided it will be removed from
the parameters.
=> Null check payload state and loginHint.

dependency-suppression.xml, library/src/main/java/com/okta/oidc/OktaAuthenticationActivity.java
Fixes approval issue with MFA authentication
on same device. This will keep CCT on the top stack.
@sergiymokiyenko-okta 
@ihormartsekha-okta
=> Remove no history flag

README.md, build.gradle
Update gradle and readme version for new release.
=> Update gradle and version

README.md, THIRD-PARTY-NOTICES, dependency-suppression.xml
Add link to authn branch in readme.
Update third party notices to include bazel.build
[OKTA-243264](https://oktainc.atlassian.net/browse/OKTA-243264)
=> README instructions to use authn android

app/build.gradle, app/src/androidTest/java/com/okta/oidc/example/MfaTest.java, app/src/androidTest/java/com/okta/oidc/example/Utils.java, app/src/main/AndroidManifest.xml, app/src/main/java/com/okta/oidc/example/PlainActivity.java, app/src/main/java/com/okta/oidc/example/SampleActivity.java, app/src/main/res/values/strings.xml, ci-build/espresso-tests.sh, dependency-suppression.xml
MFA testing with Okta Verify app.
Device needs to register okta verify.
Okta verify tests will fail until https://github.com/okta/okta-signin-widget/pull/787
is released.
[OKTA-239611](https://oktainc.atlassian.net/browse/OKTA-239611)
=> Add MFA tests

app/build.gradle, app/src/androidTest/java/com/okta/oidc/example/PlainActivityTest.java, app/src/androidTest/java/com/okta/oidc/example/Utils.java, app/src/main/java/com/okta/oidc/example/PlainActivity.java, app/src/main/res/layout/plain_activity.xml, library/src/main/java/com/okta/oidc/AuthenticationPayload.java, library/src/main/java/com/okta/oidc/net/request/web/AuthorizeRequest.java, library/src/test/java/com/okta/oidc/AuthClientPayloadTest.java
Add social login to payload. Users can set the IDP and IDP_SCOPE by using the payload methods.
Testing is done by using Google as social login provider.
[OKTA-247783](https://oktainc.atlassian.net/browse/OKTA-247783)
=> Add social login

app/build.gradle, app/src/main/AndroidManifest.xml, app/src/main/java/com/okta/oidc/example/BiometricPromptActivity.java, app/src/main/java/com/okta/oidc/example/PlainActivity.java
Use biometric prompt for authentication.
=> Use biometric prompt

app/src/main/java/com/okta/oidc/example/SampleActivity.java, library/src/main/java/com/okta/oidc/AuthenticationPayload.java, library/src/main/java/com/okta/oidc/AuthorizationStatus.java, library/src/main/java/com/okta/oidc/clients/AuthAPI.java, library/src/main/java/com/okta/oidc/clients/SyncAuthClientImpl.java, library/src/main/java/com/okta/oidc/clients/web/SyncWebAuthClientImpl.java, library/src/main/java/com/okta/oidc/clients/web/WebAuthClientImpl.java, library/src/main/java/com/okta/oidc/net/response/web/AuthorizeResponse.java, library/src/main/java/com/okta/oidc/results/Result.java, library/src/test/java/com/okta/oidc/AuthClientPayloadTest.java, library/src/test/java/com/okta/oidc/clients/web/SyncWebAuthClientTest.java, library/src/test/java/com/okta/oidc/util/TestValues.java
Handle verification response and pass result
back to application.
[OKTA-247923](https://oktainc.atlassian.net/browse/OKTA-247923)
=> Email verification flow

build.gradle
=> Update version to 1.0.4

README.md
Update readme to reflect changes in 1.0.4
=> Update readme with signout and social login

app/build.gradle, app/src/main/java/com/okta/oidc/example/EncryptedSharedPreferenceStorage.java, app/src/main/java/com/okta/oidc/example/NoEncryption.java, app/src/main/java/com/okta/oidc/example/SampleActivity.java, build.gradle
Provide a example on how to replace encryption manager by using
EncryptedSharedPreferences.
[OKTA-251177](https://oktainc.atlassian.net/browse/OKTA-251177)
=> Add sample of using encrypted shared preference

library/src/main/java/com/okta/oidc/storage/security/EncryptionManagerAPI23.java
Disable strongbox for all devices since it is causing issues with
Android 10 devices. An option to use strongbox should be added
once the issues are ironed out.
=> Disable TEE

config/checkstyle/suppression.xml, library/src/main/java/com/okta/oidc/storage/OktaRepository.java, library/src/main/java/com/okta/oidc/storage/security/BaseEncryptionManager.java
UserNotAuthenticateException doesn't exist in
API 19.
=> Fix API19 compatibility.

app/build.gradle, app/src/main/java/com/okta/oidc/example/PlainActivity.java, app/src/main/res/anim/pull_in_bottom.xml, app/src/main/res/anim/pull_in_right.xml, app/src/main/res/anim/push_out_bottom.xml, app/src/main/res/anim/push_out_right.xml, app/src/main/res/values/integers.xml, build.gradle, config/checkstyle/suppression.xml, dependency-suppression.xml, library/src/main/java/com/okta/oidc/CustomTabOptions.java, library/src/main/java/com/okta/oidc/Okta.java, library/src/main/java/com/okta/oidc/OktaAuthenticationActivity.java, library/src/main/java/com/okta/oidc/OktaResultFragment.java, library/src/main/java/com/okta/oidc/clients/web/SyncWebAuthClientFactory.java, library/src/main/java/com/okta/oidc/clients/web/SyncWebAuthClientImpl.java, library/src/main/java/com/okta/oidc/clients/web/WebAuthClientFactory.java, library/src/main/java/com/okta/oidc/clients/web/WebAuthClientImpl.java, library/src/test/java/com/okta/oidc/OktaAuthClientActivityTest.java, library/src/test/java/com/okta/oidc/OktaResultFragmentTest.java
Add options to customize the exit and entrance
animations for chrome custom tabs
[OKTA-264066](https://oktainc.atlassian.net/browse/OKTA-264066)
@okta/android
=> Ability to customize CCT animations

app/src/main/java/com/okta/oidc/example/PlainActivity.java, app/src/main/res/anim/pull_in_bottom.xml, app/src/main/res/anim/pull_in_right.xml, app/src/main/res/anim/push_out_bottom.xml, app/src/main/res/anim/push_out_right.xml, library/src/main/java/com/okta/oidc/OktaAuthenticationActivity.java
Have to override the pending animation
for authentication activity.
=> Fix CCT start animation.

README.md, build.gradle
=> Update library to 1.0.10

library/src/main/java/com/okta/oidc/OktaIdToken.java, library/src/main/java/com/okta/oidc/util/AuthorizationException.java
[OKTA-265220](https://oktainc.atlassian.net/browse/OKTA-265220)
@okta/android
=> Create new AuthorizationException type for Token Validation errors

README.md, app/build.gradle, build.gradle, gradle/wrapper/gradle-wrapper.properties
Update readme, gradle and libraries.
=> Update gradle, libraries and version

README.md, build.gradle
=> Update version to 1.0.13

README.md, app/build.gradle, build.gradle, gradle.properties, gradle/wrapper/gradle-wrapper.properties, library/build.gradle, library/src/main/java/com/okta/oidc/AuthenticationResultHandler.java, library/src/main/java/com/okta/oidc/Tokens.java, library/src/main/java/com/okta/oidc/clients/SyncAuthClientImpl.java, library/src/main/java/com/okta/oidc/clients/web/WebAuthClientImpl.java, library/src/main/java/com/okta/oidc/net/ConnectionParameters.java, library/src/main/java/com/okta/oidc/util/AuthorizationException.java, library/src/test/java/com/okta/oidc/AuthenticationResultHandlerTest.java, library/src/test/java/com/okta/oidc/TokensTest.java
- Fix bug with canceling requests
- Allow empty scopes for Oauth2.0
- Preserve exception for errors of OTHERS
- Update gradle and libraries
Internal tracking:
[OKTA-286942](https://oktainc.atlassian.net/browse/OKTA-286942)
[OKTA-315233](https://oktainc.atlassian.net/browse/OKTA-315233)
[OKTA-315234](https://oktainc.atlassian.net/browse/OKTA-315234)
=> Bug fixes and library updates

README.md
=> Update readme with java 8 requirement

README.md
=> Update readme with proguard rules

README.md
=> Update readme to use 1.0.15

README.md, build.gradle
=> Update version 1.0.16

README.md
update readme on custom signin
=> Update readme on custom sign-in setup

app/build.gradle, build.gradle, library/src/main/AndroidManifest.xml, library/src/main/java/com/okta/oidc/storage/security/EncryptionManagerAPI23.java
[OKTA-329636](https://oktainc.atlassian.net/browse/OKTA-329636)
@okta/android
=> Update to targetSDK 30

README.md, build.gradle, library/src/main/java/com/okta/oidc/storage/security/EncryptionManagerAPI18.java
This was done for a few reasons:
- Our "custom" login flow does not work in API 19/20 (this is due to a few reasons, but the hardest one to solve is ServiceLocator usage for http clients in our java commons libraries)
- Our "browser" login flow can work in API 19/20, but it's not working in any of our samples today, and it likely requires SDK updates to make work
[OKTA-269879](https://oktainc.atlassian.net/browse/OKTA-269879)
=> Update minSdk version.

README.md, library/build.gradle, library/proguard-rules.pro
This makes it automatic for consumers, removing a manual step.
Tested with `./gradlew :library:assembleRelease && ./gradlew :library:publishReleaseX` to ensure it gets put into the aar.
[OKTA-340105](https://oktainc.atlassian.net/browse/OKTA-340105)
=> Use consumer proguard rules.

README.md
Internal Ref: OKTA-342762
[OKTA-342762](https://oktainc.atlassian.net/browse/OKTA-342762)
=> Add a place to link to Discovery URI Guidance.

library/src/main/java/com/okta/oidc/OktaAuthenticationActivity.java
RESOLVES: OKTA-322515
@FeiChen-okta
=> Apply exit transition for OktaAuthenticatorActivity.

library/src/main/AndroidManifest.xml, library/src/main/java/com/okta/oidc/OktaAuthenticationActivity.java
Fix autohide custom tabs in background
[OKTA-340136](https://oktainc.atlassian.net/browse/OKTA-340136)
@okta/android
=> Fix autohide custom tabs in background

README.md, build.gradle
=> Update version to 1.0.17

build.gradle, library/src/main/java/com/okta/oidc/OktaAuthenticationActivity.java
=> OKTA-404400 Potential fix for unmarshall exception.

CHANGELOG.md, README.md, build.gradle
=> Prepare for release 1.0.20

README.md
=> Add a note about the change in maven coordinates.

CHANGELOG.md, README.md, build.gradle
=> Prepare 1.1.0 release.

CHANGELOG.md, README.md, build.gradle
=> OKTA-456478 Prepare 1.2.2 release.

.github/ISSUE_TEMPLATE/bug-report.yml, .github/ISSUE_TEMPLATE/config.yml, .github/ISSUE_TEMPLATE/feature-request.yml, .github/SECURITY.md
=> OKTA-466845 Add issue template.

CHANGELOG.md, README.md, build.gradle
=> Prepare release 1.2.3.

CHANGELOG.md, README.md, build.gradle
=> Prepare release 1.2.4.

app/build.gradle, gradle.properties
=> Update bouncy castle to 1.70.

.github/workflows/main.yml, app/build.gradle, settings.gradle
=> Fix publishing coordinates.

library/build.gradle
The new publishing plugin properly accounts for implementation, but we need to maintain backwards compatibility.
=> Make dependencies api rather than implementation to match previous releases.

README.md, app/build.gradle, build.gradle
=> OKTA-529837 Update dependencies.

RELEASING.md, app/build.gradle, build.gradle
=> Update dependencies and publishing docs.

README.md
README change to include Proguard rules
=> Add proguard setup to readme

.bacon.yml, scripts/sast_scan.sh
=> Add semgrep

app/build.gradle, build.gradle, library/build.gradle
=> Update libraries to address CVEs

build.gradle
Update checkstyle lib
[OKTA-952539](https://oktainc.atlassian.net/browse/OKTA-952539)
=> Update checkstyle version
