- library/src/main/java/com/okta/oidc/OktaAuthenticationActivity.java
When chrome custom tabs is destroyed in the background
service disconnect is called. mBound will be set to false
and unbindservice will not be called in on destroy.
So fix is to just check if connection is not null.
> Fix unbind service.

- app/build.gradle
- app/src/androidTest/java/com/okta/oidc/example/PlainActivityTest.java
- app/src/main/java/com/okta/oidc/example/PlainActivity.java
- app/src/main/res/layout/plain_activity.xml
- app/src/main/res/values/strings.xml
- library/src/main/java/com/okta/oidc/storage/security/BaseEncryptionManager.java
- library/src/main/java/com/okta/oidc/storage/security/DefaultEncryptionManager.java
- library/src/main/java/com/okta/oidc/storage/security/EncryptionManager.java
- library/src/main/java/com/okta/oidc/storage/security/EncryptionManagerAPI23.java
- library/src/main/java/com/okta/oidc/storage/security/GuardedEncryptionManager.java
- library/src/test/java/com/okta/oidc/util/EncryptionManagerStub.java
Bug was caused by removing keys and reusing the same
encryption manager object. The keys need to be recreated.
Add sample to show how to combine the encryption manager
with the keyguard. This will require the user to authenticate
the device before any profile or token calls could be done.
Espresso test added.
[OKTA-239612](https://oktainc.atlassian.net/browse/OKTA-239612)
> Fix bug when switching between encryption managers

- library/src/main/java/com/okta/oidc/storage/security/BaseEncryptionManager.java
- library/src/main/java/com/okta/oidc/storage/security/EncryptionManagerAPI23.java
Don't use the OEAP spec to initialize the cipher if
device uses strong box.
[OKTA-246722](https://oktainc.atlassian.net/browse/OKTA-246722)
> Don't use OEAP spec workaround if using strongbox.

- library/src/main/java/com/okta/oidc/clients/web/SyncWebAuthClientImpl.java
- library/src/test/java/com/okta/oidc/clients/web/SyncWebAuthClientTest.java
Current behavior is if you clear data and then
call signOutOfOkta the call will fail silently.
This change will catch that error and return
an error result.
> signOutOfOkta returns error if no tokens found.

- app/src/androidTest/java/com/okta/oidc/example/PlainActivityTest.java
- app/src/androidTest/java/com/okta/oidc/example/SampleActivityTest.java
- app/src/main/java/com/okta/oidc/example/PlainActivity.java
- app/src/main/res/layout/plain_activity.xml
- library/src/main/java/com/okta/oidc/RequestCallback.java
- library/src/main/java/com/okta/oidc/clients/AuthAPI.java
- library/src/main/java/com/okta/oidc/clients/AuthClient.java
- library/src/main/java/com/okta/oidc/clients/AuthClientImpl.java
- library/src/main/java/com/okta/oidc/clients/BaseAuth.java
- library/src/main/java/com/okta/oidc/clients/SyncAuthClient.java
- library/src/main/java/com/okta/oidc/clients/SyncAuthClientImpl.java
- library/src/main/java/com/okta/oidc/clients/web/SyncWebAuthClient.java
- library/src/main/java/com/okta/oidc/clients/web/SyncWebAuthClientImpl.java
- library/src/main/java/com/okta/oidc/clients/web/WebAuthClient.java
- library/src/main/java/com/okta/oidc/clients/web/WebAuthClientImpl.java
- library/src/test/java/com/okta/oidc/clients/SyncAuthClientTest.java
- library/src/test/java/com/okta/oidc/clients/web/SyncWebAuthClientTest.java
Helper API that does sign out by revoking tokens, signing out of browser session and
remove persistent data.
[OKTA-239591](https://oktainc.atlassian.net/browse/OKTA-239591)
> add sign out convience api

- app/src/androidTest/java/com/okta/oidc/example/EncryptionTest.java
- app/src/androidTest/java/com/okta/oidc/example/MfaTest.java
- app/src/main/java/com/okta/oidc/example/PlainActivity.java
Espresso test was failing due to payload not being provided. This cause the test for loginHint to fail.
> fix espresso tests. Add copyright notices

- library/src/main/java/com/okta/oidc/OIDCConfig.java
A common error is that developers use empty scopes. This can happen
when they put in an empty scope or have an extra comma in the json file.
This change will not allow the config to be created if scope is
incorrect.
> Validate scopes in config.

- library/src/main/java/com/okta/oidc/storage/OktaRepository.java
- library/src/main/java/com/okta/oidc/util/AuthorizationException.java
IllegalBlockSizeException is separated from
GeneralSecurityException. This makes the error message easier
to understand.
[OKTA-251171](https://oktainc.atlassian.net/browse/OKTA-251171)
> Clarify illegalblocksize encryption error.

- README.md
- library/src/main/java/com/okta/oidc/clients/sessions/SessionClient.java
authorizedRequest should not be handled by the SDK.
It is creating more problems than it solves.
Developers should add the Authorization header themselves
in http network calls.
> Deprecate authorizedRequest

- library/src/main/java/com/okta/oidc/OktaAuthenticationActivity.java
Fix a bug where if the device doesn't contain the preferred
browsers it returns null.
This fix will return the first compatible browser if none is found
from the preferred list.
> Default to first compatible browser if none found.

- README.md
- app/build.gradle
- app/src/androidTest/java/com/okta/oidc/example/EncryptionTest.java
- build.gradle
- library/build.gradle
- library/src/main/java/com/okta/oidc/CustomConfiguration.java
- library/src/main/java/com/okta/oidc/CustomTabOptions.java
- library/src/main/java/com/okta/oidc/OIDCConfig.java
- library/src/main/java/com/okta/oidc/Okta.java
- library/src/main/java/com/okta/oidc/OktaAuthenticationActivity.java
- library/src/main/java/com/okta/oidc/OktaIdToken.java
- library/src/main/java/com/okta/oidc/clients/AuthAPI.java
- library/src/main/java/com/okta/oidc/clients/sessions/SessionClientImpl.java
- library/src/main/java/com/okta/oidc/net/request/ProviderConfiguration.java
- library/src/main/java/com/okta/oidc/net/request/TokenRequest.java
- library/src/test/java/com/okta/oidc/CustomConfigurationTest.java
- library/src/test/java/com/okta/oidc/OIDCConfigTest.java
- library/src/test/java/com/okta/oidc/net/request/ConfigurationRequestTest.java
- library/src/test/java/com/okta/oidc/net/request/ProviderConfigurationTest.java
- library/src/test/java/com/okta/oidc/util/TestValues.java
Update library dependencies.
Add custom configuration for servers that doesn't support discoveryUri.
Add option to use MATCH_ALL for browser intent matching.
Fix exception handling where exceptions that are not AuthorizationException
are failing silently.
> Custom configuration option. Browser flag with match all option.

- library/src/main/java/com/okta/oidc/util/AuthorizationException.java
This moves to the androidx version of ArrayMap to fix an issue with accessing the code field of AuthorizationException class in classes under unit test in an Android project.
Resolves: #142
> :bug: Migrates to androidx.collection.ArrayMap

- library/src/main/java/com/okta/oidc/OktaAuthenticationActivity.java
- library/src/main/java/com/okta/oidc/ServiceConnection.java
- library/src/main/java/com/okta/oidc/ServiceConnectionCallback.java
Custom Tabs service may hold onto our connection (even though disconnected)
until GC.
This will prevent a leak of OktaAuthenticationActivity (thanks Leak Canary!)
https://github.com/okta/okta-oidc-android/issues/154
> Fix CustomTabsServiceConnection leak

- library/src/main/java/com/okta/oidc/storage/OktaRepository.java
The cacheStorage is only populated during a `save` operation, but never when there is a cache miss during a `get`.
An application using the SDK from a cold start will never have the cache populated and the encryption/decryption operation will be always performed (performance impact)
> Fix storage cache not always populated

- library/src/main/java/com/okta/oidc/net/HttpResponse.java
- library/src/main/java/com/okta/oidc/net/HttpStatusCodeException.java
- library/src/test/java/com/okta/oidc/net/HttpResponseTest.java
Prerequisite to: OKTA-282915
Adds a new `HttpStatusCodeException` that subclasses `IOException` that is thrown when an unexpected status code is encountered on parsing the response as JSON, in place of a plain IOException.
This change is transparent to existing consumers that are unaware of `HttpStatusCodeException`. The underlying exception message remains the same as before.
[OKTA-282915](https://oktainc.atlassian.net/browse/OKTA-282915)
@FeiChen-okta
> HttpResponse: Throw HttpStatusCodeException when unexpected status code is encountered

- library/src/main/java/com/okta/oidc/OktaAuthenticationActivity.java
Switching to singleInstance to fix taskAffinity leaves
CCT in the backstack. Fix this by setting no history.
> Add no history flag to custom tab intent

- library/src/main/java/com/okta/oidc/OktaBuilder.java
obvious fix
code to initialize the default `HttpClientImpl()` was included twice in the `createAuthClient()` method.
> Remove duplicate creation of default HttpClient

- app/src/main/AndroidManifest.xml
- library/src/main/AndroidManifest.xml
I recently created a new project using this SDK. I found it surprising that I had to add internet permission to the manifest given that this SDK was using internet for getting the `.well-known/openid-configuration` endpoint.
> Add internet permission to library manifest.

- library/src/main/java/com/okta/oidc/storage/security/BaseEncryptionManager.java
Some devices when attempting to get the certificate chain
and the public key returns null.
> Attempt to fix null certificate

- library/src/main/java/com/okta/oidc/clients/sessions/SessionClientImpl.java
- library/src/test/java/com/okta/oidc/clients/sessions/SessionClientImplTest.java
Canceling requests is causing exceptions, rather than cancel the previous request, let's run them in serial, before we can rearchitect to run them in parallel. 
This is a working solution, with minimal changes to avoid unexpected breakage. Another approach would have been to rewrite `RequestDispatcher`, but I decided against it until a rearchitecture. 
[OKTA-431176](https://oktainc.atlassian.net/browse/OKTA-431176)
> OKTA-431176 Run SessionClient requests in serial.

- library/src/main/java/com/okta/oidc/storage/OktaRepository.java
See https://github.com/google/tink/blob/cb814f1e1b69caf6211046bee083a730625a3cf9/java_src/src/main/java/com/google/crypto/tink/integration/android/AndroidKeystoreAesGcm.java for influence.
Fixes #310
> OKTA-488271 Sleep and retry when crypto operations fail.

- library/src/main/java/com/okta/oidc/clients/web/SyncWebAuthClientImpl.java
Make a cancelled sign in report as cancelled rather than with an error.
Closes #318 
> Cancelling should get a cancelled response.

- README.md
- library/src/main/java/com/okta/oidc/net/request/TokenRequest.java
- library/src/main/java/com/okta/oidc/net/response/TokenResponse.java
- library/src/test/java/com/okta/oidc/net/request/TokenRequestTest.java
- library/src/test/java/com/okta/oidc/net/response/TokenResponseTest.java
- library/src/test/java/com/okta/oidc/util/JsonStrings.java
- library/src/test/java/com/okta/oidc/util/MockEndPoint.java
This PR validates TokenResponse for required parameters before returning the TokenResponse. Otherwise, an AuthorizationException is thrown. access_token, token_type, and expires_in are all required parameters in okta-mobile-kotlin, and so those are the parameters being validated.
Also, reverted an earlier README update which was redundant due to existing [proguard-rules.pro](https://github.com/okta/okta-oidc-android/tree/master/library/proguard-rules.pro) in the SDK.
> Validate TokenResponse

- library/src/main/java/com/okta/oidc/OktaAuthenticationActivity.java
Copied over the browser querying logic from okta-mobile-kotlin, which avoids having to use matchAll flag when the default system browser doesn't support chrome custom tabs.
> Use browser querying logic from okta-mobile-kotlin
